name: sks
favicon: null
layout_spectrum: 0.48547
typography_spectrum: 1
title: South Kent School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#666666'
    - '#b50839'
    - '#e6a9ba'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.9417476847302169
purpose: []
